name: CI/CD Pipeline for Iris Regression

on:
  push:
    branches: [ main ]

jobs:
  iris_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: ğŸ“¦ Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: ğŸ§  Train Model (Pipeline Stage)
        run: |
          echo "Starting model training..."
          python app.py
          echo "Model training finished."

      - name: ğŸ³ Build Docker Image
        run: docker build -t iris-regression .

      - name: ğŸš€ Run Docker Container
        run: docker run iris-regression
